services:
  server:
    build: ./server
    container_name: rbac-task-server
    ports:
      - "8800:8800"
    env_file:
      - ./server/.env
    restart: always

  client:
    build: ./client
    container_name: rbac-task-client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - server
    restart: always
